//
//  Strings.swift
//  PAMFlow
//
//  Created by Dory on 18/06/2026.
//

/// User-facing strings grouped by feature module.
///
/// Keeping strings centralized makes copy updates and future localization less
/// error-prone as the app expands beyond audio workflows.
public enum Strings {
    public enum Common {
        public static let unknown = "Unknown"
        public static let unreviewed = "Unreviewed"
        public static let reviewed = "Reviewed"
        public static let unknownUser = "Unknown user"
        public static let other = "Other"
        public static let backToProjects = "Back to Projects"
        public static let back = "Back"
        public static let home = "Home"
        public static let settingsButton = "Settings"
        public static let loggedInPrefix = "logged in as"
        public static let projectNotFound = "Project could not be found."
        public static let cancel = "Cancel"
        public static let close = "Close"
        public static let showInFinder = "Show in Finder"
        public static let status = "Status"
        public static let yes = "Yes"
        public static let notYet = "Not yet"
    }

    public enum DataTypeSelection {
        public static let title = "What type of data would you like to process?"
    }

    public enum ProjectSelection {
        public static let title = "Projects"
        public static let subtitle = "Pick up where you left off or start a new batch."
        public static let newProjectButton = "New Project"
        public static let emptyTitle = "No projects yet"
        public static let emptySubtitle = "Create a project to start processing data."
        public static let lastCompletedPrefix = "Last completed:"
        public static let manualAuditProgressPrefix = "Manual audit:"
        public static let detectionReviewProgressPrefix = "Detection review:"
        public static let frameReviewProgressPrefix = "Frame review:"
        public static let recorderPrefix = "Recorder:"
        public static let lastOpenedPrefix = "Last opened:"
        public static let missingFolder = "Missing folder"
        public static let viewAvailableDataButton = "View Available Data"
        public static let deleteButton = "Delete"
        public static let startProcessingButton = "Start Processing"
        public static let processingCompleted = "Processing completed"
        public static let startFrameReviewButton = "Start Frame Review"
        public static let openFrameReviewOverviewButton = "Open Frame Review Overview"
        public static let continueManualReviewButton = "Continue Manual Review"
        public static let continueFrameReviewButton = "Continue Frame Review"
        public static let deleteConfirmationTitle = "Delete Project?"
        public static let deleteConfirmationMessage = "This permanently deletes the saved project and its project folder."
        public static let deleteConfirmationButton = "Delete Project"
        public static let deleteConfirmationCancelButton = "Cancel"
        public static let searchPlaceholder = "Search projects"
        public static let noMatchingProjects = "No matching projects."
        public static let inProgressGroup = "In Progress"
        public static let completedGroup = "Completed"
        public static let frameReviewInProgress = "Frame review in progress"
        public static let frameReviewCompleted = "Frame review completed"
        public static let progressFormat = "%d of %d"
        public static let zeroReviewed = "0 reviewed"
    }

    public enum ProjectSetup {
        public static let title = "Create Project"
        public static let backButton = "Back to Projects"
        public static let subtitle = "Select one recorder's raw data."
        public static let projectNamePlaceholder = "Project name"
        public static let recorderPickerTitle = "Recorder"
        public static let recorderPlaceholder = "Select recorder"
        public static let singleRecorderHint = "Use data from one recorder or camera only. Create a separate project for each source."
        public static let inputSelectionGuidance = "Choose a folder for the smoothest setup, or select specific files for a smaller project."
        public static let folderSelectionGuidance = "The project folder will be created inside this raw data folder."
        public static let fileSelectionGuidance = "The project folder will be created next to these files. macOS may ask you once to allow access to that folder."
        public static let inputFolderButton = "Select Raw Data"
        public static let createButton = "Create PAMFlow Project"
        public static let createdPrefix = "Created:"
        public static let metadataTitleFormat = "%@ metadata"
        public static let uploadCSV = "Upload CSV"
        public static let enterManually = "Enter manually"
        public static let opcode = "Opcode"
        public static let selectOpcode = "Select Opcode"
        public static let date = "Date"
        public static let dateDeployed = "Date deployed"
        public static let dateRetrieved = "Date retrieved"
        public static let location = "Location"
        public static let depth = "Depth"
        public static let bottomType = "Bottom type"
        public static let waterTemperature = "Water temperature"
        public static let done = "Done"
        public static let uploadMetadataCSVTitleFormat = "Upload %@ metadata CSV"
        public static let pamMetadataUploadMessage = "Choose a CSV table containing Opcode, Date deployed, Date retrieved, Location, Depth, and Bottom type."
        public static let visualMetadataUploadMessage = "Choose a CSV table containing Opcode, Date, Location, Depth, Bottom type, and Water temperature."
        public static let inputPanelTitle = "Select Raw Data"
        public static let inputPanelMessage = "Choose a folder or select multiple raw data files for one recorder or camera."
        public static let projectFolderPermissionTitle = "Allow Project Folder Access"
        public static let projectFolderPermissionMessage = "PAMFlow can read the selected files, but macOS needs one more folder permission before the project can be saved beside them. Select the raw media folder and click Allow."
        public static let missingInputFolder = "Select the folder containing raw data files."
        public static let missingRecorder = "Select which recorder this data comes from."
        public static let missingProjectName = "Enter a project name."
    }

    public enum ScanProject {
        public static let title = "Scanning Project"
        public static let backButton = "Back to Project Creation"
        public static let subtitle = "Inspecting data files and calculating technical evidence."
        public static let preparing = "Preparing scan..."
        public static let preparingMessage = preparing
        public static let finalizing = "Finalizing scan..."
        public static let finalizingMessage = finalizing
        public static let cancelTitle = "Cancel Scan?"
        public static let cancelMessage = "Going back removes the current project and all scan progress made so far."
        public static let cancelConfirmButton = "Remove Project and Go Back"
        public static let cancelDismissButton = "Stay Here"
    }

    public enum NewProjectOverview {
        public static let title = "Project Overview"
        public static let subtitle = "Review the scan results before manual audit starts."
        public static let backButton = "Back to Project Creation"
        public static let projectName = "Project name"
        public static let recorderID = "Recorder ID"
        public static let inputFolder = "Input folder"
        public static let filesFound = "Files found"
        public static let totalSize = "Total size"
        public static let durationRange = "Duration range"
        public static let channels = "Channel counts found"
        public static let formats = "Formats found"
        public static let resolutions = "Resolutions found"
        public static let frameCountRange = "Frame count range"
        public static let imageCount = "Image count"
        public static let mediaProperties = "Media properties"
        public static let qualityWarnings = "Quality warnings"
        public static let estimatedBatchSize = "Estimated batch size"
        public static let manualAuditProgress = "Manual audit progress"
        public static let startManualAuditButton = "Start Manual Audit"
        public static let startProcessingButton = "Start Processing"
        public static let skipManualAuditButton = "Skip Manual Audit"
        public static let skipManualAuditHelp = "Use every scanned file as valid input for the next step."
        public static let startFrameReviewButton = "Start Frame Review"
        public static let continueManualAuditButton = "Continue Manual Audit"
        public static let continueFrameReviewButton = "Continue Frame Review"
        public static let openManualAuditOverviewButton = "Open Manual Audit Overview"
        public static let openFrameReviewOverviewButton = "Open Frame Review Overview"
        public static let ready = "Ready for manual audit"
        public static let readyForProcessing = "Ready for processing"
        public static let processingInProgress = "Processing detections..."
        public static let processingBlocked = "Processing needs attention."
        public static let notReady = "No supported files were found."
        public static let unknown = "Unknown"
        public static let typicalLength = "Typical length"
        public static let filesFoundFormat = "%@ found"
        public static let filesNeedAttentionFormat = "%d files need attention."
        public static let noFilesNeedAttention = "No files need attention"
        public static let attention = "Attention"
        public static let wavFiles = "WAV files"
        public static let videoFiles = "video files"
        public static let imageFiles = "image files"
        public static let commonDurationFormat = "Most files are %@"
        public static let durationCouldNotBeEstimated = "Duration could not be estimated"
        public static let filesNeedAttentionPlainFormat = "%d files need attention"
        public static let notReadyForManualAudit = "Not ready for manual audit"
        public static let notReadyForProcessing = "Not ready for processing"
        public static let largeBatch = "Large"
        public static let mediumBatch = "Medium"
        public static let smallBatch = "Small"
        public static let moduleProcessingTitle = "Processing"
        public static let cancelTitle = "Go Back to Project Creation?"
        public static let cancelMessage = "Going back removes this project folder, scan results, and any audit progress so you can create it again cleanly."
        public static let cancelConfirmButton = "Remove Project and Go Back"
        public static let cancelDismissButton = "Stay Here"
        public static let backToScanTitle = "Go Back to Scan?"
        public static let backToScanMessage = "Going back to scan will remove the current manual review progress for this project."
        public static let backToScanConfirmButton = "Remove Review Progress"
        public static let reviewedPercentFormat = "%d of %d reviewed (%d%%)"
    }

    public enum ManualAudit {
        public static let title = "Manual Audit"
        public static let frameReviewTitle = "Frame Review"
        public static let sampleProgressFormat = "Sample %d/%d"
        public static let detectionProgressFormat = "Detection %d/%d"
        public static let backToOverview = "Back to Overview"
        public static let loadingPreview = "Loading preview"
        public static let previewUnavailable = "Preview is unavailable for this file."
        public static let scanEvidence = "File Details"
        public static let fileName = "File name"
        public static let decision = "Decision"
        public static let notReviewed = "Not reviewed"
        public static let quality = "Quality"
        public static let frameNumber = "Frame number"
        public static let maxN = "maxN"
        public static let frameCount = "Frame count"
        public static let frameRate = "Frame rate"
        public static let imageSize = "Image size"
        public static let format = "Format"
        public static let fileSize = "File size"
        public static let duration = "Duration"
        public static let sampleRate = "Sample rate"
        public static let channels = "Channels"
        public static let bitDepth = "Bit depth"
        public static let peak = "Peak"
        public static let rms = "RMS"
        public static let clipping = "Clipping"
        public static let nearZero = "Near zero"
        public static let previous = "Previous"
        public static let previousWithArrow = "< Previous"
        public static let next = "Next"
        public static let nextWithArrow = "Next >"
        public static let finishAudit = "Finish"
        public static let species = "Species"
        public static let assignSpecies = "Assign Species"
        public static let speciesAssignedFormat = "%d species assigned"
        public static let trackID = "Track ID"
        public static let confidence = "Confidence"
        public static let deleteDetection = "Delete Detection"
        public static let restoreDetection = "Restore Detection"
        public static let noSpecies = "No species selected"
        public static let reviewedSuffix = "reviewed"
        public static let previousSampleHelp = "Previous sample"
        public static let chooseDecisionBeforeNextHelp = "Choose a decision before moving forward"
        public static let nextSampleHelp = "Next sample"
        public static let chooseDecisionBeforeFinishHelp = "Choose a decision before finishing"
        public static let openManualAuditOverviewHelp = "Open manual audit overview"
        public static let detectionReviewTitle = "Detection Review"
        public static let detectionID = "Detection ID"
        public static let startTime = "Start time"
        public static let endTime = "End time"
        public static let selectedSpeciesPrefixFormat = "Species: %@"
        public static let selectedReasonPrefixFormat = "Reason: %@"
    }

    public enum AuditReason {
        public static let addReason = "Add Reason"
        public static let reason = "Reason"
        public static let deploymentNoise = "Deployment noise"
        public static let fileCorrupted = "File corrupted"
        public static let falsePositive = "False positive"
        public static let clearReason = "Clear Reason"
        public static let saveReason = "Save Reason"
    }

    public enum SpeciesSelection {
        public static let title = "Assign Species"
        public static let assignedSpecies = "Assigned species"
        public static let noSpeciesAssigned = "No species assigned"
        public static let item = "Track ID"
        public static let score = "Confidence"
        public static let searchPlaceholder = "Search scientific or common name"
        public static let taxonomy = "Taxonomy"
        public static let assign = "Assign"
        public static let close = "Close"
        public static let family = "Family"
        public static let genus = "Genus"
        public static let species = "Species"
        public static let fullName = "Full name"
        public static let clear = "Clear"
        public static let cancel = "Cancel"
        public static let save = "Save Species"
        public static let detection = "Detection"
        public static let noDetection = "No detection"
        public static let discardTitle = "Discard Changes?"
        public static let discardMessage = "Your species assignment changes have not been saved."
        public static let discardChanges = "Discard Changes"
    }

    public enum ManualAuditOverview {
        public static let title = "Manual Audit Overview"
        public static let frameReviewTitle = "Detection Overview"
        public static let subtitle = "Review the human audit decisions before preparing the processing step."
        public static let reviewedFormat = "%d of %d reviewed"
        public static let project = "Project"
        public static let readyForProcessing = "Ready for processing"
        public static let readyForExport = "Ready for export"
        public static let valid = "Valid"
        public static let unsure = "Unsure"
        public static let invalid = "Invalid"
        public static let remaining = "Remaining"
        public static let sourceRecordings = "Source recordings"
        public static let detectionTables = "Detection tables"
        public static let frequencyRange = "Frequency range"
        public static let imageSize = "Image size"
        public static let formats = "Formats"
        public static let detections = "Detections"
        public static let originalDetections = "Original detections"
        public static let confirmedDetections = "Confirmed detections"
        public static let detectionsByRecording = "Detections by recording"
        public static let speciesCounts = "Species counts"
        public static let noSpeciesSelected = "No species selected"
        public static let decisionBreakdown = "Decision breakdown"
        public static let originalSamples = "Original samples"
        public static let validSamples = "Valid samples"
        public static let invalidReasons = "Invalid reasons"
        public static let showLess = "Show less"
        public static let showAll = "Show all"
        public static let backToAudit = "Back to Audit"
        public static let reviewDetections = "Review Detections"
        public static let continueToReport = "Continue to Report"
        public static let finishAuditHelp = "Finish manual audit before continuing"
        public static let reviewDetectionsHelp = "Review remaining detections"
        public static let reportHelp = "Open the reviewed detection report"
        public static let reviewedTitleFormat = "of %d reviewed"
        public static let noReviewFramesCreated = "No review frames were created. The project can still be completed and exported with zero detections."
    }

    public enum ProjectCompletion {
        public static let title = "Detection overview"
        public static let subtitle = "Review and export confirmed detections."
        public static let folderUnavailableTitle = "Project folder unavailable"
        public static let folderUnavailableMessage = "PAMFlow can still show saved project details and review decisions, but media files, generated previews, and exports are unavailable until the project folder or drive is connected again."
        public static let savedDecisions = "saved decisions"
        public static let projectOverview = "Project overview"
        public static let project = "Project"
        public static let type = "Type"
        public static let processedBy = "Processed by"
        public static let projectFolder = "Project folder"
        public static let inputFolder = "Input folder"
        public static let opcode = "Opcode"
        public static let date = "Date"
        public static let dateDeployed = "Date deployed"
        public static let dateRetrieved = "Date retrieved"
        public static let location = "Location"
        public static let depth = "Depth"
        public static let bottomType = "Bottom type"
        public static let waterTemperature = "Water temperature"
        public static let deleteProject = "Delete Project"
        public static let exportDetections = "Export Detections"
        public static let complete = "Complete"
        public static let reportFields = "Report fields"
        public static let reportFieldsSubtitle = "Export columns, in order"
        public static let customiseFields = "Customise Fields"
        public static let resetDefaults = "Reset Defaults"
        public static let saveFields = "Save Fields"
        public static let customiseFieldsSubtitle = "Drag selected fields to reorder them. Add only the detection fields you want in the export."
        public static let selected = "Selected"
        public static let selectedSubtitle = "Drag rows, or use the arrow buttons."
        public static let available = "Available"
        public static let availableSubtitle = "Click to add a field."
        public static let exportSuccessFormat = "Exported %@. Project marked completed."
        public static let completionSaveFailed = "The export was created, but PAMFlow could not update the project status. Please try again or reopen the project."
    }

    public enum WorkflowStatus {
        public static let created = "Created"
        public static let inProgress = "In progress"
        public static let scanInProgress = "Scan in progress"
        public static let scanCompleted = "Scan completed"
        public static let manualAuditInProgress = "Manual audit in progress"
        public static let manualAuditCompleted = "Manual audit completed"
        public static let processingProjectCreated = "Processing project created"
        public static let processingRunImported = "Processing run imported"
        public static let runOverviewCompleted = "Run overview completed"
        public static let detectionReviewInProgress = "Detection review in progress"
        public static let completed = "Completed"
        public static let projectCreated = "Project created"
        public static let allDetectionsReviewed = "All detections reviewed"
        public static let resumeScan = "Resume Scan"
        public static let continueToOverview = "Continue to Overview"
        public static let continueManualAudit = "Continue Manual Audit"
        public static let openAuditOverview = "Open Audit Overview"
        public static let importProcessingRun = "Import Processing Run"
        public static let openRunOverview = "Open Run Overview"
        public static let continueDetectionReview = "Continue Detection Review"
        public static let viewProject = "View Project"
    }

    public enum AppTheme {
        public static let system = "System"
        public static let light = "Light"
        public static let dark = "Dark"
    }

    public enum ExportFields {
        public static let eventID = "Event ID"
        public static let fileID = "File ID"
        public static let eventStartSeconds = "Event Start Seconds"
        public static let eventEndSeconds = "Event End Seconds"
        public static let score = "Score"
        public static let evidenceTypes = "Evidence Types"
        public static let detectors = "Detectors"
        public static let clickCount = "Click Count"
        public static let clickBoutCount = "Click Bout Count"
        public static let clickTrainCount = "Click Train Count"
        public static let whistleCount = "Whistle Count"
        public static let qualityFlags = "Quality Flags"
        public static let reviewStatus = "Review Status"
        public static let detectionID = "Detection ID"
        public static let opcode = "Opcode"
        public static let dateDeployed = "Date Deployed"
        public static let dateRetrieved = "Date Retrieved"
        public static let location = "Location"
        public static let depth = "Depth"
        public static let bottomType = "Bottom Type"
        public static let waterTemperature = "Water Temperature"
        public static let fileName = "File Name"
        public static let detectionFile = "Detection file"
        public static let relativePath = "Relative Path"
        public static let sourceMedia = "Source Media"
        public static let processedBy = "Processed by"
        public static let decision = "Decision"
        public static let reason = "Reason"
        public static let speciesFamily = "Species Family"
        public static let speciesGenus = "Species Genus"
        public static let speciesName = "Species Name"
        public static let speciesFullName = "Species Full Name"
        public static let durationSeconds = "Duration Seconds"
        public static let clipStartSeconds = "Clip Start Seconds"
        public static let clipDurationSeconds = "Clip Duration Seconds"
        public static let sampleRateHz = "Sample Rate Hz"
        public static let channels = "Channels"
        public static let bitDepth = "Bit Depth"
        public static let peakDBFS = "Peak dBFS"
        public static let rmsDBFS = "RMS dBFS"
        public static let detector = "Detector"
        public static let frameNumber = "Frame Number"
        public static let trackID = "Track ID"
        public static let maxN = "maxN"
        public static let confidence = "Confidence"
        public static let frameCount = "Frame Count"
        public static let frameRate = "Frame Rate"
        public static let width = "Width"
        public static let height = "Height"
        public static let format = "Format"
        public static let sizeBytes = "Size Bytes"
        public static let qualityFlag = "Quality Flag"
        public static let qualityReasons = "Quality Reasons"
    }

    public enum Welcome {
        public static let title = "Welcome to PAMFlow"
        public static let subtitle = "Enter your name so the app can track who processed each sample."
        public static let namePlaceholder = "Your name"
        public static let continueButton = "Continue"
    }

    public enum Settings {
        public static let title = "Settings"
        public static let backButton = "Back"
        public static let appearanceTitle = "Appearance"
        public static let aboutTitle = "About"
        public static let version = "Version"
        public static let versionFormat = "%@ (%@)"
        public static let copyright = "Copyright © 2026"
        public static let copyrightOwner = "Dory"
        public static let copyrightURL = "https://github.com/dorypiacek"
        public static let feedbackTitle = "Send Feedback"
        public static let feedbackEmailPlaceholder = "Email address (optional)"
        public static let feedbackSubjectPlaceholder = "Subject"
        public static let feedbackMessagePlaceholder = "Message"
        public static let addAttachmentsButton = "Add Attachments"
        public static let sendFeedbackButton = "Send Feedback"
        public static let maxAttachmentBytes = 10 * 1_024 * 1_024
        public static let maxAttachmentSizeLabel = "10 MB"
        public static let attachmentLimitMessage = "Attachment limit is 10 MB so the email can still be sent."
        public static let feedbackOpenedMessage = "Email draft opened. Choose the sending account in Mail before sending."
        public static let logOutButton = "Log Out"
        public static let doneButton = "Done"
    }
}
