//
//  Strings.swift
//  PAMFlow
//
//  Created by Dory on 18/06/2026.
//

/// User-facing strings grouped by feature module.
///
/// Keeping strings centralized makes copy updates and future localization less
/// error-prone as the app expands beyond audio workflows.
enum Strings {
    enum Common {
        static let unknown = "Unknown"
        static let unreviewed = "Unreviewed"
        static let reviewed = "Reviewed"
        static let unknownUser = "Unknown user"
        static let other = "Other"
        static let backToProjects = "Back to Projects"
        static let back = "Back"
        static let home = "Home"
        static let settingsButton = "Settings"
        static let loggedInPrefix = "logged in as"
        static let projectNotFound = "Project could not be found."
        static let cancel = "Cancel"
        static let close = "Close"
        static let showInFinder = "Show in Finder"
        static let status = "Status"
        static let yes = "Yes"
        static let notYet = "Not yet"
    }

    enum DataTypeSelection {
        static let title = "What type of data would you like to process?"
        static let pamAudioTitle = "PAM Audio"
        static let pamAudioSubtitle = "WAV recordings for PAMGuard-based acoustic review."
        static let bruvVideoTitle = "BRUV Video"
        static let bruvVideoSubtitle = "Video files for SharkTrack detection review."
        static let ruvImageTitle = "RUV Images"
        static let ruvImageSubtitle = "Image batches for SharkTrack detection review."
    }

    enum ProjectSelection {
        static let title = "Projects"
        static let subtitle = "Pick up where you left off or start a new batch."
        static let newProjectButton = "New Project"
        static let emptyTitle = "No projects yet"
        static let emptySubtitle = "Create a project to start processing data."
        static let lastCompletedPrefix = "Last completed:"
        static let manualAuditProgressPrefix = "Manual audit:"
        static let frameReviewProgressPrefix = "Frame review:"
        static let recorderPrefix = "Recorder:"
        static let lastOpenedPrefix = "Last opened:"
        static let missingFolder = "Missing folder"
        static let viewAvailableDataButton = "View Available Data"
        static let deleteButton = "Delete"
        static let startProcessingButton = "Start Processing"
        static let processingCompleted = "Processing completed"
        static let startFrameReviewButton = "Start Frame Review"
        static let openFrameReviewOverviewButton = "Open Frame Review Overview"
        static let continueManualReviewButton = "Continue Manual Review"
        static let continueFrameReviewButton = "Continue Frame Review"
        static let pamguardSetupReady = "PAMGuard setup ready"
        static let openPamguardSetupButton = "Open PAMGuard Setup"
        static let waitingForPamguard = "Waiting for PAMGuard"
        static let openPamguardWaitingButton = "Open PAMGuard"
        static let pamguardSetupCompleted = "PAMGuard setup completed"
        static let deleteConfirmationTitle = "Delete Project?"
        static let deleteConfirmationMessage = "This permanently deletes the saved project and its project folder."
        static let deleteConfirmationButton = "Delete Project"
        static let deleteConfirmationCancelButton = "Cancel"
        static let searchPlaceholder = "Search projects"
        static let noMatchingProjects = "No matching projects."
        static let inProgressGroup = "In Progress"
        static let completedGroup = "Completed"
        static let frameReviewInProgress = "Frame review in progress"
        static let frameReviewCompleted = "Frame review completed"
        static let zeroReviewed = "0 reviewed"
    }

    enum ProjectSetup {
        static let title = "Create Project"
        static let backButton = "Back to Projects"
        static let subtitle = "Select one recorder's raw data."
        static let projectNamePlaceholder = "Project name"
        static let recorderPickerTitle = "Recorder"
        static let recorderPlaceholder = "Select recorder"
        static let singleRecorderHint = "Use data from one recorder or camera only. Create a separate project for each source."
        static let inputSelectionGuidance = "Choose a folder for the smoothest setup, or select specific files for a smaller project."
        static let folderSelectionGuidance = "The project folder will be created inside this raw data folder."
        static let fileSelectionGuidance = "The project folder will be created next to these files. macOS may ask you once to allow access to that folder."
        static let inputFolderButton = "Select Raw Data"
        static let createButton = "Create PAMFlow Project"
        static let createdPrefix = "Created:"
        static let metadataTitleFormat = "%@ metadata"
        static let uploadCSV = "Upload CSV"
        static let enterManually = "Enter manually"
        static let opcode = "Opcode"
        static let selectOpcode = "Select Opcode"
        static let date = "Date"
        static let dateDeployed = "Date deployed"
        static let dateRetrieved = "Date retrieved"
        static let location = "Location"
        static let depth = "Depth"
        static let bottomType = "Bottom type"
        static let waterTemperature = "Water temperature"
        static let done = "Done"
        static let uploadMetadataCSVTitleFormat = "Upload %@ metadata CSV"
        static let pamMetadataUploadMessage = "Choose a CSV table containing Opcode, Date deployed, Date retrieved, Location, Depth, and Bottom type."
        static let visualMetadataUploadMessage = "Choose a CSV table containing Opcode, Date, Location, Depth, Bottom type, and Water temperature."
        static let inputPanelTitle = "Select Raw Data"
        static let inputPanelMessage = "Choose a folder or select multiple raw data files for one recorder or camera."
        static let projectFolderPermissionTitle = "Allow Project Folder Access"
        static let projectFolderPermissionMessage = "PAMFlow can read the selected files, but macOS needs one more folder permission before the project can be saved beside them. Select the raw media folder and click Allow."
        static let missingInputFolder = "Select the folder containing raw data files."
        static let missingRecorder = "Select which recorder this data comes from."
        static let missingProjectName = "Enter a project name."
    }

    enum ScanProject {
        static let title = "Scanning Project"
        static let backButton = "Back to Project Creation"
        static let subtitle = "Inspecting data files and calculating technical evidence."
        static let preparing = "Preparing scan..."
        static let preparingMessage = preparing
        static let finalizing = "Finalizing scan..."
        static let finalizingMessage = finalizing
        static let cancelTitle = "Cancel Scan?"
        static let cancelMessage = "Going back removes the current project and all scan progress made so far."
        static let cancelConfirmButton = "Remove Project and Go Back"
        static let cancelDismissButton = "Stay Here"
    }

    enum NewProjectOverview {
        static let title = "Project Overview"
        static let subtitle = "Review the scan results before manual audit starts."
        static let backButton = "Back to Project Creation"
        static let projectName = "Project name"
        static let recorderID = "Recorder ID"
        static let inputFolder = "Input folder"
        static let filesFound = "Files found"
        static let totalSize = "Total size"
        static let durationRange = "Duration range"
        static let sampleRates = "Sample rates found"
        static let channels = "Channel counts found"
        static let bitDepths = "Bit depths found"
        static let formats = "Formats found"
        static let resolutions = "Resolutions found"
        static let frameRates = "Frame rates found"
        static let frameCountRange = "Frame count range"
        static let imageCount = "Image count"
        static let mediaProperties = "Media properties"
        static let qualityWarnings = "Quality warnings"
        static let estimatedBatchSize = "Estimated batch size"
        static let manualAuditProgress = "Manual audit progress"
        static let startManualAuditButton = "Start Manual Audit"
        static let startProcessingButton = "Start Processing"
        static let skipManualAuditButton = "Skip Manual Audit"
        static let skipManualAuditHelp = "Use every scanned audio file as PAMGuard input."
        static let startFrameReviewButton = "Start Frame Review"
        static let continueManualAuditButton = "Continue Manual Audit"
        static let continueFrameReviewButton = "Continue Frame Review"
        static let openManualAuditOverviewButton = "Open Manual Audit Overview"
        static let openFrameReviewOverviewButton = "Open Frame Review Overview"
        static let ready = "Ready for manual audit"
        static let readyForProcessing = "Ready for processing"
        static let processingInProgress = "Processing detections..."
        static let processingBlocked = "Processing needs attention."
        static let notReady = "No supported files were found."
        static let unknown = "Unknown"
        static let typicalLength = "Typical length"
        static let filesFoundFormat = "%@ found"
        static let filesNeedAttentionFormat = "%d files need attention."
        static let noFilesNeedAttention = "No files need attention"
        static let attention = "Attention"
        static let wavFiles = "WAV files"
        static let videoFiles = "video files"
        static let imageFiles = "image files"
        static let commonDurationFormat = "Most files are %@"
        static let durationCouldNotBeEstimated = "Duration could not be estimated"
        static let filesNeedAttentionPlainFormat = "%d files need attention"
        static let notReadyForManualAudit = "Not ready for manual audit"
        static let notReadyForProcessing = "Not ready for processing"
        static let largeBatch = "Large"
        static let mediumBatch = "Medium"
        static let smallBatch = "Small"
        static let sharkTrackTitle = "SharkTrack detections"
        static let sharkTrackPreparing = "Preparing SharkTrack detections..."
        static let sharkTrackReady = "SharkTrack detections are ready."
        static let sharkTrackReadyNotice = "Ready to process detections with SharkTrack."
        static let cancelTitle = "Go Back to Project Creation?"
        static let cancelMessage = "Going back removes this project folder, scan results, and any audit progress so you can create it again cleanly."
        static let cancelConfirmButton = "Remove Project and Go Back"
        static let cancelDismissButton = "Stay Here"
        static let backToScanTitle = "Go Back to Scan?"
        static let backToScanMessage = "Going back to scan will remove the current manual review progress for this project."
        static let backToScanConfirmButton = "Remove Review Progress"
        static let reviewedPercentFormat = "%d of %d reviewed (%d%%)"
    }

    enum ManualAudit {
        static let title = "Manual Audit"
        static let frameReviewTitle = "Frame Review"
        static let sampleProgressFormat = "Sample %d/%d"
        static let detectionProgressFormat = "Detection %d/%d"
        static let backToOverview = "Back to Overview"
        static let loadingPreview = "Loading preview"
        static let previewUnavailable = "Preview is unavailable for this file."
        static let scanEvidence = "File Details"
        static let fileName = "File name"
        static let decision = "Decision"
        static let notReviewed = "Not reviewed"
        static let quality = "Quality"
        static let sourceVideo = "Video filename"
        static let frameNumber = "Frame number"
        static let maxN = "maxN"
        static let frameCount = "Frame count"
        static let frameRate = "Frame rate"
        static let imageSize = "Image size"
        static let format = "Format"
        static let fileSize = "File size"
        static let sharkTrackStatus = "SharkTrack status"
        static let duration = "Duration"
        static let sampleRate = "Sample rate"
        static let channels = "Channels"
        static let bitDepth = "Bit depth"
        static let peak = "Peak"
        static let rms = "RMS"
        static let clipping = "Clipping"
        static let nearZero = "Near zero"
        static let previous = "Previous"
        static let previousWithArrow = "< Previous"
        static let next = "Next"
        static let nextWithArrow = "Next >"
        static let finishAudit = "Finish"
        static let species = "Species"
        static let assignSpecies = "Assign Species"
        static let speciesAssignedFormat = "%d species assigned"
        static let trackID = "Track ID"
        static let confidence = "Confidence"
        static let deleteDetection = "Delete Detection"
        static let restoreDetection = "Restore Detection"
        static let noSpecies = "No species selected"
        static let reviewedSuffix = "reviewed"
        static let previousSampleHelp = "Previous sample"
        static let pauseHelp = "Pause"
        static let playHelp = "Play"
        static let chooseDecisionBeforeNextHelp = "Choose a decision before moving forward"
        static let nextSampleHelp = "Next sample"
        static let chooseDecisionBeforeFinishHelp = "Choose a decision before finishing"
        static let openManualAuditOverviewHelp = "Open manual audit overview"
        static let detectionReviewTitle = "Detection Review"
        static let detectionID = "Detection ID"
        static let startTime = "Start time"
        static let endTime = "End time"
        static let amplitude = "Amplitude"
        static let timeAxis = "Time (s)"
        static let frequencyAxis = "Frequency (Hz)"
        static let displayRange = "display range: 50 dB"
        static let selectedSpeciesPrefixFormat = "Species: %@"
        static let selectedReasonPrefixFormat = "Reason: %@"
    }

    enum AuditReason {
        static let addReason = "Add Reason"
        static let reason = "Reason"
        static let deploymentNoise = "Deployment noise"
        static let fileCorrupted = "File corrupted"
        static let falsePositive = "False positive"
        static let clearReason = "Clear Reason"
        static let saveReason = "Save Reason"
    }

    enum SpeciesSelection {
        static let title = "Assign Species"
        static let assignedSpecies = "Assigned species"
        static let noSpeciesAssigned = "No species assigned"
        static let searchPlaceholder = "Search scientific or common name"
        static let taxonomy = "Taxonomy"
        static let assign = "Assign"
        static let close = "Close"
        static let family = "Family"
        static let genus = "Genus"
        static let species = "Species"
        static let fullName = "Full name"
        static let clear = "Clear"
        static let cancel = "Cancel"
        static let save = "Save Species"
        static let detection = "Detection"
        static let noDetection = "No detection"
        static let discardTitle = "Discard Changes?"
        static let discardMessage = "Your species assignment changes have not been saved."
        static let discardChanges = "Discard Changes"
    }

    enum ManualAuditOverview {
        static let title = "Manual Audit Overview"
        static let frameReviewTitle = "Detection Overview"
        static let audioDetectionTitle = "Audio Detection Overview"
        static let subtitle = "Review the human audit decisions before preparing the processing step."
        static let audioDetectionSubtitle = "Review the PAMGuard detection decisions before creating the export."
        static let reviewedFormat = "%d of %d reviewed"
        static let project = "Project"
        static let readyForProcessing = "Ready for processing"
        static let readyForPamguard = "Ready for PAMGuard"
        static let readyForExport = "Ready for export"
        static let valid = "Valid"
        static let unsure = "Unsure"
        static let invalid = "Invalid"
        static let remaining = "Remaining"
        static let sourceRecordings = "Source recordings"
        static let detectionTables = "Detection tables"
        static let frequencyRange = "Frequency range"
        static let sourceVideos = "Source videos"
        static let imageSize = "Image size"
        static let formats = "Formats"
        static let detections = "Detections"
        static let originalDetections = "Original detections"
        static let confirmedDetections = "Confirmed detections"
        static let processedVideos = "Processed videos"
        static let detectionsByVideo = "Detections by video"
        static let detectionsByRecording = "Detections by recording"
        static let speciesCounts = "Species counts"
        static let noSpeciesSelected = "No species selected"
        static let decisionBreakdown = "Decision breakdown"
        static let originalSamples = "Original samples"
        static let validSamples = "Valid samples"
        static let invalidReasons = "Invalid reasons"
        static let showLess = "Show less"
        static let showAll = "Show all"
        static let backToAudit = "Back to Audit"
        static let goToPamguardSetup = "Go to PAMGuard Setup"
        static let continueToReport = "Continue to Report"
        static let finishAuditHelp = "Finish manual audit before continuing"
        static let preparePamguardHelp = "Prepare PAMGuard files"
        static let reportHelp = "Open the reviewed detection report"
        static let reviewedTitleFormat = "of %d reviewed"
        static let noReviewFramesCreated = "No review frames were created. The project can still be completed and exported with zero detections."
    }

    enum ProjectScan {
        nonisolated static let scanningFileFormat = "Scanning file %d/%d"
        nonisolated static let noSupportedFilesFound = "No supported files found."
        nonisolated static let supportedFilesFoundFormat = "Found %d supported files."
        nonisolated static let imageMetadataUnreadable = "Image metadata could not be read."
        nonisolated static let videoTrackUnreadable = "Video track could not be read."
        nonisolated static let videoMetadataUnreadable = "Video metadata could not be read."
        nonisolated static let missingProjectFolder = "Could not open the project folder."
        nonisolated static let missingInputFolder = "Could not open the selected input folder."
        nonisolated static let missingSummaryFormat = "Scan did not create %@."
        nonisolated static let noWAVFilesFound = "No WAV files were found."
        nonisolated static let noVideoFilesFound = "No video files were found."
        nonisolated static let noImageFilesFound = "No image files were found."
        nonisolated static let unreadableFilesFound = "Some files could not be read."
        nonisolated static let multipleSampleRatesFound = "Multiple sample rates found."
        nonisolated static let clippedFilesFound = "Some files are clipped."
        nonisolated static let nearlyEmptyFilesFound = "Some files are nearly empty."
    }

    enum SharkTrackProcessing {
        static let title = "Processing Detections"
        static let subtitle = "SharkTrack is finding candidate animals for frame review."
        static let preparingMessage = "Preparing SharkTrack..."
        static let processingFileFormat = "Processing file %d/%d: %@"
        static let processingFrameFormat = "Processing frame %d/%d"
        static let remainingFormat = "About %@ remaining"
        static let estimatingRemaining = "Estimating time remaining..."
        static let silentRuntimeFormat = "Processing for %@. SharkTrack has not reported frame progress yet."
        static let processingDetectionFormat = "%d detections found"
        static let finalizingMessage = "Finalizing detections..."
        static let failedMessage = "SharkTrack processing failed."
        static let noDetectionsMessage = "No review frames were created."
        static let unknownDuration = "unknown time"
        static let retryButton = "Retry Processing"
    }

    enum SharkTrackProgress {
        nonisolated static let started = "SharkTrack processing started."
        nonisolated static let simulatedCompletedFormat = "Simulated SharkTrack processing completed with %d detections."
        nonisolated static let completedFormat = "SharkTrack processing completed with %d detections."
    }

    enum PAMGuardDetectionProgress {
        nonisolated static let readingBinary = "Reading PAMGuard binary detections..."
        nonisolated static let readingDatabaseFallback = "Reading PAMGuard database fallback..."
        nonisolated static let groupingEvents = "Grouping PAMGuard detections into events..."
        nonisolated static let preparingEventFormat = "Preparing event %d/%d"
        nonisolated static let eventsReady = "PAMGuard events are ready for review."
        nonisolated static let decodingBinaryFileFormat = "Decoding binary file %d/%d"
    }

    enum PAMGuardPreparationError {
        nonisolated static let missingProjectFolder = "Project folder could not be opened."
        nonisolated static let missingInputFolder = "Input folder could not be opened."
        nonisolated static let missingTemplate = "The PAMGuard template is missing from the app bundle."
        nonisolated static let noAuditedInputFiles = "No valid or unsure audio files were found in the audit."
        nonisolated static let inputSymlinkFailedFormat = "The PAMGuard input links could not be created: %@"
        nonisolated static let databaseCreationFailedFormat = "The PAMGuard database could not be created: %@"
        nonisolated static let sqliteSymbolsMissing = "SQLite symbols could not be loaded."
        nonisolated static let sqliteOpenFailedFormat = "SQLite open failed with code %d."
        nonisolated static let sqliteInitializationFailedFormat = "SQLite initialization failed with code %d."
    }

    enum PAMGuardDetectionError {
        nonisolated static let missingProjectFolder = "Could not open the project folder."
        nonisolated static let missingInputFolder = "Could not open the input folder."
        nonisolated static let missingDatabase = "No PAMGuard SQLite database was found in the pamguard/db folder."
        nonisolated static let missingBinaryFolder = "No PAMGuard binary folder was found at pamguard/binary."
        nonisolated static let sqliteOpenFailedFormat = "The PAMGuard SQLite database could not be opened: %@"
        nonisolated static let noDetectionsFound = "No PAMGuard detections were found in the binary or database outputs."
    }

    enum ProjectCompletion {
        static let title = "Detection overview"
        static let subtitle = "Review and export confirmed detections."
        static let folderUnavailableTitle = "Project folder unavailable"
        static let folderUnavailableMessage = "PAMFlow can still show saved project details and review decisions, but media files, generated previews, and exports are unavailable until the project folder or drive is connected again."
        static let savedDecisions = "saved decisions"
        static let projectOverview = "Project overview"
        static let project = "Project"
        static let type = "Type"
        static let processedBy = "Processed by"
        static let projectFolder = "Project folder"
        static let inputFolder = "Input folder"
        static let opcode = "Opcode"
        static let date = "Date"
        static let dateDeployed = "Date deployed"
        static let dateRetrieved = "Date retrieved"
        static let location = "Location"
        static let depth = "Depth"
        static let bottomType = "Bottom type"
        static let waterTemperature = "Water temperature"
        static let deleteProject = "Delete Project"
        static let exportDetections = "Export Detections"
        static let complete = "Complete"
        static let reportFields = "Report fields"
        static let reportFieldsSubtitle = "Export columns, in order"
        static let customiseFields = "Customise Fields"
        static let resetDefaults = "Reset Defaults"
        static let saveFields = "Save Fields"
        static let customiseFieldsSubtitle = "Drag selected fields to reorder them. Add only the detection fields you want in the export."
        static let selected = "Selected"
        static let selectedSubtitle = "Drag rows, or use the arrow buttons."
        static let available = "Available"
        static let availableSubtitle = "Click to add a field."
        static let exportSuccessFormat = "Exported %@. Project marked completed."
        static let completionSaveFailed = "The export was created, but PAMFlow could not update the project status. Please try again or reopen the project."
    }

    enum WorkflowStatus {
        static let created = "Created"
        static let scanInProgress = "Scan in progress"
        static let scanCompleted = "Scan completed"
        static let manualAuditInProgress = "Manual audit in progress"
        static let manualAuditCompleted = "Manual audit completed"
        static let processingProjectCreated = "Processing project created"
        static let processingRunImported = "Processing run imported"
        static let runOverviewCompleted = "Run overview completed"
        static let detectionReviewInProgress = "Detection review in progress"
        static let completed = "Completed"
        static let projectCreated = "Project created"
        static let allDetectionsReviewed = "All detections reviewed"
        static let resumeScan = "Resume Scan"
        static let continueToOverview = "Continue to Overview"
        static let continueManualAudit = "Continue Manual Audit"
        static let openAuditOverview = "Open Audit Overview"
        static let importProcessingRun = "Import Processing Run"
        static let openRunOverview = "Open Run Overview"
        static let continueDetectionReview = "Continue Detection Review"
        static let viewProject = "View Project"
    }

    enum WorkflowModule {
        nonisolated static let pamTitle = "PAM"
        nonisolated static let bruvTitle = "BRUV"
        nonisolated static let ruvTitle = "RUV"
        nonisolated static let audioFolder = "Audio"
        nonisolated static let bruvVideoFolder = "BRUV Video"
        nonisolated static let ruvImagesFolder = "RUV Images"
    }

    enum AppTheme {
        static let system = "System"
        static let light = "Light"
        static let dark = "Dark"
    }

    enum ExportFields {
        static let eventID = "Event ID"
        static let fileID = "File ID"
        static let eventStartSeconds = "Event Start Seconds"
        static let eventEndSeconds = "Event End Seconds"
        static let score = "Score"
        static let evidenceTypes = "Evidence Types"
        static let detectors = "Detectors"
        static let clickCount = "Click Count"
        static let clickBoutCount = "Click Bout Count"
        static let clickTrainCount = "Click Train Count"
        static let whistleCount = "Whistle Count"
        static let qualityFlags = "Quality Flags"
        static let reviewStatus = "Review Status"
        static let detectionID = "Detection ID"
        static let opcode = "Opcode"
        static let dateDeployed = "Date Deployed"
        static let dateRetrieved = "Date Retrieved"
        static let location = "Location"
        static let depth = "Depth"
        static let bottomType = "Bottom Type"
        static let waterTemperature = "Water Temperature"
        static let fileName = "File Name"
        static let detectionFile = "Detection file"
        static let relativePath = "Relative Path"
        static let sourceMedia = "Source Media"
        static let processedBy = "Processed by"
        static let decision = "Decision"
        static let reason = "Reason"
        static let speciesFamily = "Species Family"
        static let speciesGenus = "Species Genus"
        static let speciesName = "Species Name"
        static let speciesFullName = "Species Full Name"
        static let durationSeconds = "Duration Seconds"
        static let clipStartSeconds = "Clip Start Seconds"
        static let clipDurationSeconds = "Clip Duration Seconds"
        static let sampleRateHz = "Sample Rate Hz"
        static let channels = "Channels"
        static let bitDepth = "Bit Depth"
        static let peakDBFS = "Peak dBFS"
        static let rmsDBFS = "RMS dBFS"
        static let detector = "Detector"
        static let frameNumber = "Frame Number"
        static let trackID = "Track ID"
        static let maxN = "maxN"
        static let confidence = "Confidence"
        static let frameCount = "Frame Count"
        static let frameRate = "Frame Rate"
        static let width = "Width"
        static let height = "Height"
        static let format = "Format"
        static let sizeBytes = "Size Bytes"
        static let qualityFlag = "Quality Flag"
        static let qualityReasons = "Quality Reasons"
    }

    enum PAMDetectionPackage {
        static let sourceRecordingNotFound = "Source recording not found"
        static let noGroupedDetectionEvents = "No grouped detection events"
        static let unprocessedStatus = "unprocessed"
        static let processedStatus = "processed"
        static let timeAxis = "Time (s)"
        static let frequencyAxis = "Frequency (Hz)"
        static let spectrogramView = "Spectrogram 1"
        static let fallbackSampleName = "sample"

        static let sampleCSVHeader = [
            "sampleId", "opcode", "recordingFile", "dateDeployed", "dateRetrieved", "location", "depth", "bottomType", "sampleRateHz", "channels", "durationSeconds", "processedBy", "processingStatus", "originalDetectionCount", "confirmedDetectionCount", "exclusionReason"
        ]
        static let eventCSVHeader = [
            "eventId", "sampleId", "opcode", "recordingFile", "channel", "startDateTimeUTC", "endDateTimeUTC", "startOffsetSeconds", "endOffsetSeconds", "durationSeconds", "detectorType", "detectionCount", "minFrequencyHz", "maxFrequencyHz", "processedBy", "reviewStatus", "eventValidity", "reviewer", "notes"
        ]
        static let ravenHeader = [
            "Selection", "View", "Channel", "Begin Time (s)", "End Time (s)", "Low Freq (Hz)", "High Freq (Hz)", "Begin File", "Event ID", "Detector", "Review Status"
        ]
    }

    enum PAMGuardSetup {
        static let title = "PAMGuard Setup"
        static let subtitle = "Prepare the PAMGuard template and audited audio inputs."
        static let backButton = "Back to Manual Audit Overview"
        static let question = "What would you like to detect?"
        static let selectDetectionTarget = "Select detection target"
        static let pygmyKillerWhales = "Pygmy killer whales"
        static let generalOdontocetes = "General odontocetes"
        static let preparing = "Preparing PAMGuard files..."
        static let prepared = "PAMGuard template is ready."
        static let showInFinder = "Show in Finder"
        static let instructions = "Open PAMGuard in Normal mode and select the generated template."
        static let continueButton = "Continue"
        static let selectedInputCountFormat = "%d audited audio files linked"
        static let waitingTitle = "Waiting for PAMGuard detections"
        static let waitingSubtitle = "Run the generated template in PAMGuard, then confirm when detections are finished."
        static let confirmRunFinished = "PAMGuard run is finished"
        static let helpButton = "PAMGuard help"
        static let helpTitle = "Run PAMGuard"
        static let helpDownloadStep = "Download PAMGuard for macOS. Apple Silicon is required."
        static let helpDownloadLink = "PAMGuard V2.02.18 release page"
        static let helpStep1 = "Open PAMGuard and select Normal mode."
        static let helpStep2 = "Open the generated pamguard folder and select the .psfx as the template."
        static let helpStep3 = "In PAMGuard, choose File -> Database -> Database Selection, then select the .sqlite file from the db folder."
        static let helpStep4 = "Choose File -> Binary Store -> Storage options, then select the binary folder."
        static let helpStep5 = "Choose File -> Show Data Model, right-click Sound Acquisition, select Settings, and choose the input folder."
        static let helpStep6 = "Close the data model and click Play, the red circle button."
        static let helpStep7 = "Wait for PAMGuard to finish, then return to PAMFlow."
    }

    enum PAMGuardProcessing {
        static let title = "Processing PAMGuard Detections"
        static let subtitle = "Importing the PAMGuard run and preparing detection review."
        static let starting = "Starting PAMGuard detection import..."
        static let failed = "PAMGuard detection import failed."
        static let retry = "Retry Import"
    }

    enum Welcome {
        static let title = "Welcome to PAMFlow"
        static let subtitle = "Enter your name so the app can track who processed each sample."
        static let namePlaceholder = "Your name"
        static let continueButton = "Continue"
    }

    enum Settings {
        static let title = "Settings"
        static let backButton = "Back"
        static let appearanceTitle = "Appearance"
        static let aboutTitle = "About"
        static let version = "Version"
        static let versionFormat = "%@ (%@)"
        static let copyright = "Copyright © 2026"
        static let copyrightOwner = "Dory"
        static let copyrightURL = "https://github.com/dorypiacek"
        static let feedbackTitle = "Send Feedback"
        static let feedbackEmailPlaceholder = "Email address (optional)"
        static let feedbackSubjectPlaceholder = "Subject"
        static let feedbackMessagePlaceholder = "Message"
        static let addAttachmentsButton = "Add Attachments"
        static let sendFeedbackButton = "Send Feedback"
        static let maxAttachmentBytes = 10 * 1_024 * 1_024
        static let maxAttachmentSizeLabel = "10 MB"
        static let attachmentLimitMessage = "Attachment limit is 10 MB so the email can still be sent."
        static let feedbackOpenedMessage = "Email draft opened. Choose the sending account in Mail before sending."
        static let logOutButton = "Log Out"
        static let doneButton = "Done"
    }
}
